- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Build the custom Jenkins Docker image
      docker_image:
        path: ./
        name: custom/jenkins
    - name: Run Jenkins Docker image
      docker_container:
        name: jenkins
        image: custom/jenkins
        published_ports: 8080:8080
    - name: Create Crumb Remote Access Request Field
      uri:
        url: 'http://127.0.0.1:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
        user: jenkins-admin
        password: jenkins-admin-password
        force_basic_auth: yes
        return_content: yes
      register: crumb
    - name: Create Global Sauce Lab Credentials
      uri:
        method: POST
        url: 'http://127.0.0.1:8080/credentials/store/system/domain/_/createCredentials'
        user: jenkins-admin
        password: jenkins-admin-password
        force_basic_auth: yes
        headers:
          Jenkins-Crumb: "{{ crumb.content.split(':')[1] }}"
        body: |
          json={
            "":"0",
            "credentials":{
              "scope":"GLOBAL",
              "id":"sauce-id",
              "description":"sauce labs auth",
              "username":"your-saucelabs-username",
              "apiKey":"your-saucelabs-access-key",
              "restEndpoint":"https://saucelabs.com/",
              "$class":"hudson.plugins.sauce_ondemand.credentials.SauceCredentials"
            }
          }
        status_code: 302