version: 2
jobs:
  build:
    working_directory: /repo
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk update
            apk upgrade
            apk add --no-cache --virtual \
             .build-deps g++ python3-dev libffi-dev curl openssl-dev && \
            apk add --no-cache --update python3 && \
            pip3 install --upgrade pip setuptools
      - run:
          name: Install Docker and Ansible
          command: |
            pip3 install \
              docker \
              ansible
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/demo-jenkins.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/demo-jenkins.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=demo-jenkins -t demo-jenkins .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/demo-jenkins.tar demo-jenkins
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/demo-jenkins.tar
      - run:
          name: Run Docker Image
          command: |
            docker run \
            --name demo-jenkins \
            -u root \
            --rm \
            -d \
            -p 8080:8080 \
            -p 50000:50000 \
            -v jenkins-data:/var/jenkins_home \
            -v /var/run/docker.sock:/var/run/docker.sock \
            demo-jenkins
      - run:
          name: Check Running Container
          command: |
            docker ps
#      - run:
#          name: Set Jenkins Credentials
#          no_output_timeout: 5m
#          command: |
#            JENKINS_CRUMB=$(curl -s 'http://jenkins-admin:jenkins-admin-password@127.0.0.1:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')
#            curl -s -XPOST -H ${JENKINS_CRUMB} http://jenkins-admin:jenkins-admin-password@127.0.0.1:8080/credentials/store/system/domain/_/createCredentials \
#            --data-urlencode 'json={
#              "": "0",
#              "credentials": {
#                "scope": "GLOBAL",
#                "id": "credential_id_here",
#                "username": ${SAUCE_USERNAME},
#                "password": ${SAUCE_ACCESS_KEY},
#                "description": "My new credentials",
#                "$class": "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"
#              }
#            }'
      - run:
          name: Stop Containers
          command: |
            docker stop $(docker ps -aq)
#      - run:
#          name: Execute Ansible Playbook
#          command: |
#            ansible-playbook jenkins-docker-build-and-deploy.yml
#      - run:
#          name: Run tests
#          command: |
#            docker-compose -f ./docker-compose.test.yml up
#      - deploy:
#          name: Push application Docker image
#          command: |
#              docker tag demo-jenkins "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
#              docker demo-jenkins "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"